openapi: 3.0.3
info:
  title: Gratia Auth Service API
  version: "1.0.0"
  description: Authentication service for Gratia project

servers:
  - url: /api/v1/auth

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - full_name
                - email
                - password
                - phone_number
                - role
              properties:
                full_name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                phone_number:
                  type: string
                role:
                  type: string
                  enum: [restaurant, ngo, admin]
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user_id:
                    type: string
                    format: uuid
        '400':
          description: Invalid input data
        '409':
          description: Email already in use
        '500':
          description: Internal server error

  /login:
    post:
      summary: Login user and receive JWT tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  expires_in:
                    type: integer
                  token_type:
                    type: string
        '401':
          description: Invalid email or password
        '403':
          description: User account is disabled
        '500':
          description: Internal server error

  /me:
    get:
      summary: Get current logged-in user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Invalid or expired token
        '500':
          description: Internal server error

  /logout:
    post:
      summary: Logout user (invalidate session token)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Invalid or expired token
        '500':
          description: Internal server error

  /refresh:
    post:
      summary: Refresh access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refresh_token
              properties:
                refresh_token:
                  type: string
      responses:
        '200':
          description: New access token issued
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  expires_in:
                    type: integer
                  token_type:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        full_name:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
        phone_number:
          type: string
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
